name: Deploy hexo blog

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4.2.2
       # with:
          #submodules: recursive  # 初始化子模块
         # fetch-depth: 0  # 拉取完整历史记录，避免子模块更新问题
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.4.0
        with:

          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "centaurea9"
          git config --global user.email "centaurea1016@gmail.com"
      - name: Install dependeninstalles
        run: |
          npm i -g hexo-cli
          npm install
         
          npm install
          npm run build
          
      - name: Deploy hexo
        run: |
          hexo clean
          hexo d -g